spring:
  devtools:
    livereload:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://${auth0.domain}/"
          audiences: "http://localhost"

auth0:
  domain: dev-milessmiles.auth0.com
  apitoken: ""

mosaic:
  oms:
    frontend:
      url: http://localhost:5173
---

spring:
  config:
    activate:
      on-profile: dev


  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
management:
  info:
    env:
      enabled: true
    git:
      mode: full
  endpoints:
    jmx:
      exposure:
        include: health,info,env,beans
    web:
      exposure:
        include: health,info,env,beans
