spring:
  devtools:
    livereload:
      enabled: false

---

spring:
  config:
    activate:
      on-profile: dev


  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
management:
  info:
    env:
      enabled: true
    git:
      mode: full
  endpoints:
    jmx:
      exposure:
        include: health,info,env,beans
    web:
      exposure:
        include: health,info,env,beans
