server:
  servlet:
    session:
      timeout: 15m
      cookie:
        same-site: strict
  error:
    include-stacktrace: never

spring:
  devtools:
    restart:
      enabled: false
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://${auth0.domain}/"
          audiences: "http://localhost"
  flyway:
    out-of-order: true

auth0:
  domain: dev-milessmiles.auth0.com
  managementAudience: "https://dev-milessmiles.auth0.com/api/v2/"

mosaic:
  oms:
    frontend:
      url: http://localhost:5173
management:
  endpoints:
    web:
      base-path: /api/actuator

cap-metro:
  api:
    trip-updates:
      path: https://data.texas.gov/download/rmk2-acnw/application%2Foctet-stream
---
spring:
  config:
    activate:
      on-profile: dev
    livereload:
      enabled: false

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
management:
  info:
    env:
      enabled: true
    git:
      mode: full
  endpoints:
    jmx:
      exposure:
        include: health,info,env,beans
    web:
      exposure:
        include: health,info,env,beans

hazelcast:
  network:
    join:
      multicast:
        enabled: false


---

spring:
  config:
    activate:
      on-profile: prod
  devtools:
    livereload:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://${auth0.domain}/"
          audiences: "https://mosaic.miles-smiles.us"

auth0:
  domain: dev-milessmiles.auth0.com

mosaic:
  oms:
    frontend:
      url: https://mosaic.miles-smiles.us

management:
  info:
    git:
      mode: full
  endpoints:
    jmx:
      exposure:
        include: health,info
    web:
      exposure:
        include: health,info

hazelcast:
  network:
    join:
      multicast:
        enabled: false
      tcp-ip:
        enabled: false
      aws:
        enabled: true
    interfaces:
      enabled: true
      interfaces:
        - 172.30.*.*
